class GameConfig:
    FIRST_TEAM_CARDS = 9
    SECOND_TEAM_CARDS = 8
    ASSASSIN_CARDS = 1
    NEUTRAL_CARDS = 7
    NUM_CARDS = FIRST_TEAM_CARDS + SECOND_TEAM_CARDS + ASSASSIN_CARDS + NEUTRAL_CARDS
    NUM_WORDS = 25
    WORD_LIST = []